### ISSUE TITLE
Move this to Website and Remove Repo

### ISSUE THREAD

**Issue by katamaritaco** [UW-UPL/webcam#1]
This seems deprecated, but not 100% sure. If it is, we should add to 'archived' repo

**Comment by mjneil** [comment]
@squeakrats consolidated this into another script for his lab status code. He should handle moving and removing this to make sure everything needed is moved

**Comment by melutzke** [comment]
Make sure you preserve the Arduino code or you're gonna have a bad time

**Comment by katamaritaco** [comment]
I'll throw this into the archive
